---
version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=sampledb
    - POSTGRES_PASSWORD=sampledb
    - POSTGRES_USER=sampledb
    - PGDATA=/database
  tests:
    depends_on: db
    image: obliquo/nanogo
    entrypoint: /usr/bin/make
    command: test

